MAHARATNA_PSUS = [
    {"name": "Bharat Heavy Electricals Limited", "short": "BHEL", "url": "https://www.bhel.com/careers"},
    {"name": "Bharat Petroleum Corporation Limited", "short": "BPCL", "url": "https://www.bharatpetroleum.in/careers"},
    {"name": "Coal India Limited", "short": "CIL", "url": "https://www.coalindia.in/careers"},
    {"name": "GAIL (India) Limited", "short": "GAIL", "url": "https://gailonline.com/careers"},
    {"name": "Hindustan Petroleum Corporation Limited", "short": "HPCL", "url": "https://www.hpclcareers.com"},
    {"name": "Indian Oil Corporation Limited", "short": "IOCL", "url": "https://iocl.com/careers"},
    {"name": "NTPC Limited", "short": "NTPC", "url": "https://www.ntpccareers.net"},
    {"name": "Oil and Natural Gas Corporation Limited", "short": "ONGC", "url": "https://www.ongcindia.com/careers"},
    {"name": "Power Finance Corporation Limited", "short": "PFC", "url": "https://www.pfcindia.com/careers"},
    {"name": "REC Limited", "short": "REC", "url": "https://www.recindia.com/careers"},
    {"name": "Oil India Limited", "short": "OIL", "url": "https://www.oil-india.com/careers"},
    {"name": "Power Grid Corporation of India Limited", "short": "PGCIL", "url": "https://www.powergrid.in/careers"},
    {"name": "Steel Authority of India Limited", "short": "SAIL", "url": "https://www.sail.co.in/careers"},
    {"name": "Hindustan Aeronautics Limited", "short": "HAL", "url": "https://hal-india.co.in/careers"},
]

NAVRATNA_PSUS = [
    {"name": "Bharat Electronics Limited", "short": "BEL", "url": "https://bel-india.in/careers"},
    {"name": "Container Corporation of India Limited", "short": "CONCOR", "url": "https://www.concorindia.com/careers"},
    {"name": "Engineers India Limited", "short": "EIL", "url": "https://www.engineersindia.com/careers"},
    {"name": "Mahanagar Telephone Nigam Limited", "short": "MTNL", "url": "https://www.mtnl.co.in/careers"},
    {"name": "National Aluminium Company Limited", "short": "NALCO", "url": "https://www.nalcoindia.com/careers"},
    {"name": "National Buildings Construction Corporation", "short": "NBCC", "url": "https://www.nbccindia.com/careers"},
    {"name": "NMDC Limited", "short": "NMDC", "url": "https://www.nmdc.co.in/careers"},
    {"name": "Rashtriya Ispat Nigam Limited", "short": "RINL", "url": "https://www.vizagsteel.com/careers"},
    {"name": "Shipping Corporation of India Limited", "short": "SCI", "url": "https://www.shipindia.com/careers"},
    {"name": "Telecommunications Consultants India Limited", "short": "TCIL", "url": "https://www.tcil.net.in/careers"},
]

MINIRATNA_I_PSUS = [
    {"name": "Airports Authority of India", "short": "AAI", "url": "https://www.aai.aero/careers"},
    {"name": "Antrix Corporation Limited", "short": "ANTRIX", "url": "https://www.antrix.co.in/careers"},
    {"name": "Balmer Lawrie & Company Limited", "short": "BALMER", "url": "https://www.balmerlawrie.com/careers"},
    {"name": "Bharat Coking Coal Limited", "short": "BCCL", "url": "https://www.bcclweb.in/careers"},
    {"name": "Bharat Dynamics Limited", "short": "BDL", "url": "https://www.bdl-india.in/careers"},
    {"name": "BEML Limited", "short": "BEML", "url": "https://www.bemlindia.com/careers"},
    {"name": "Bharat Sanchar Nigam Limited", "short": "BSNL", "url": "https://www.bsnl.co.in/careers"},
    {"name": "Bridge & Roof Company (India) Limited", "short": "BRIDGE", "url": "https://www.bridgeroof.co.in/careers"},
    {"name": "Central Coalfields Limited", "short": "CCL", "url": "https://www.centralcoalfields.in/careers"},
    {"name": "Central Electronics Limited", "short": "CEL", "url": "https://www.celindia.co.in/careers"},
    {"name": "Central Mine Planning & Design Institute Limited", "short": "CMPDI", "url": "https://www.cmpdi.co.in/careers"},
    {"name": "Central Warehousing Corporation", "short": "CWC", "url": "https://www.cewacor.nic.in/careers"},
    {"name": "Cochin Shipyard Limited", "short": "CSL", "url": "https://www.cochinshipyard.com/careers"},
    {"name": "Dredging Corporation of India Limited", "short": "DCI", "url": "https://www.dredge-india.com/careers"},
    {"name": "Energy Efficiency Services Limited", "short": "EESL", "url": "https://www.eeslindia.org/careers"},
    {"name": "Engineering Projects (India) Limited", "short": "EPI", "url": "https://www.epi.co.in/careers"},
    {"name": "Ferro Scrap Nigam Limited", "short": "FSNL", "url": "https://www.fsnl.co.in/careers"},
    {"name": "Food Corporation of India", "short": "FCI", "url": "https://www.fci.gov.in/careers"},
    {"name": "Garden Reach Shipbuilders & Engineers Limited", "short": "GRSE", "url": "https://www.grse.in/careers"},
    {"name": "Goa Shipyard Limited", "short": "GSL", "url": "https://www.goashipyard.co.in/careers"},
    {"name": "Hindustan Copper Limited", "short": "HCL", "url": "https://www.hindustancopper.com/careers"},
    {"name": "HLL Lifecare Limited", "short": "HLL", "url": "https://www.lifecarehll.com/careers"},
    {"name": "HSCC (India) Limited", "short": "HSCC", "url": "https://www.hsccindia.com/careers"},
    {"name": "India Tourism Development Corporation", "short": "ITDC", "url": "https://www.itdc.co.in/careers"},
    {"name": "Indian Rare Earths Limited", "short": "IREL", "url": "https://www.irel.gov.in/careers"},
    {"name": "Indian Renewable Energy Development Agency", "short": "IREDA", "url": "https://www.ireda.in/careers"},
    {"name": "KIOCL Limited", "short": "KIOCL", "url": "https://www.kiocl.in/careers"},
    {"name": "Mazagon Dock Shipbuilders Limited", "short": "MDL", "url": "https://www.mazagondock.in/careers"},
    {"name": "Mahanadi Coalfields Limited", "short": "MCL", "url": "https://www.mcl.gov.in/careers"},
    {"name": "Manganese Ore (India) Limited", "short": "MOIL", "url": "https://www.moil.nic.in/careers"},
    {"name": "Mishra Dhatu Nigam Limited", "short": "MIDHANI", "url": "https://www.midhani.gov.in/careers"},
    {"name": "MSTC Limited", "short": "MSTC", "url": "https://www.mstcindia.co.in/careers"},
    {"name": "National Fertilizers Limited", "short": "NFL", "url": "https://www.nationalfertilizers.com/careers"},
    {"name": "National Projects Construction Corporation", "short": "NPCC", "url": "https://www.npcc.gov.in/careers"},
    {"name": "National Small Industries Corporation", "short": "NSIC", "url": "https://www.nsic.co.in/careers"},
    {"name": "NHPC Limited", "short": "NHPC", "url": "https://www.nhpcindia.com/careers"},
    {"name": "NLC India Limited", "short": "NLC", "url": "https://www.nlcindia.com/careers"},
    {"name": "Numaligarh Refinery Limited", "short": "NRL", "url": "https://www.nrl.co.in/careers"},
    {"name": "Pyrites, Phosphates & Chemicals Limited", "short": "PPCL", "url": ""},
    {"name": "Rashtriya Chemicals & Fertilizers Limited", "short": "RCF", "url": "https://www.rcfltd.com/careers"},
    {"name": "SJVN Limited", "short": "SJVN", "url": "https://www.sjvn.nic.in/careers"},
    {"name": "Security Printing and Minting Corporation of India", "short": "SPMCIL", "url": "https://www.spmcil.com/careers"},
    {"name": "South Eastern Coalfields Limited", "short": "SECL", "url": "https://www.secl.gov.in/careers"},
    {"name": "State Trading Corporation of India", "short": "STC", "url": "https://www.stc.gov.in/careers"},
    {"name": "THDC India Limited", "short": "THDC", "url": "https://www.thdc.co.in/careers"},
    {"name": "Uranium Corporation of India Limited", "short": "UCIL", "url": "https://www.ucil.gov.in/careers"},
    {"name": "Water & Power Consultancy Services", "short": "WAPCOS", "url": "https://www.wapcos.gov.in/careers"},
    {"name": "Western Coalfields Limited", "short": "WCL", "url": "https://www.westerncoalfields.com/careers"},
]

MINIRATNA_II_PSUS = [
    {"name": "Bharat Immunological & Biologicals Corporation", "short": "BIBCOL", "url": ""},
    {"name": "Cotton Corporation of India", "short": "CCI", "url": "https://www.cotcorp.org.in/careers"},
    {"name": "Export Credit Guarantee Corporation", "short": "ECGC", "url": "https://www.ecgc.in/careers"},
    {"name": "FCI Aravali Gypsum & Minerals India Limited", "short": "FAGMIL", "url": ""},
    {"name": "Hindustan Newsprint Limited", "short": "HNL", "url": ""},
    {"name": "Hindustan Salts Limited", "short": "HSL", "url": ""},
    {"name": "Jute Corporation of India", "short": "JCI", "url": "https://www.juteindia.com/careers"},
    {"name": "National Film Development Corporation", "short": "NFDC", "url": "https://www.nfdcindia.com/careers"},
    {"name": "National Handicapped Finance & Development Corporation", "short": "NHFDC", "url": ""},
    {"name": "National Scheduled Castes Finance & Development Corporation", "short": "NSFDC", "url": ""},
    {"name": "National Seed Corporation", "short": "NSC", "url": "https://www.inderseed.com/careers"},
    {"name": "Neelachal Ispat Nigam Limited", "short": "NINL", "url": ""},
    {"name": "Rajasthan Electronics & Instruments Limited", "short": "REIL", "url": "https://www.reil.co.in/careers"},
    {"name": "Sambhar Salts Limited", "short": "SSL", "url": ""},
    {"name": "Sidhartha Apparels Limited", "short": "SAL", "url": ""},
    {"name": "Tamil Nadu Telecommunications Limited", "short": "TNTL", "url": ""},
]

OTHER_PSUS = [
    {"name": "Electronics Corporation of India Limited", "short": "ECIL", "url": "https://www.ecil.co.in/careers"},
    {"name": "Bhabha Atomic Research Centre", "short": "BARC", "url": "https://www.barc.gov.in/careers"},
    {"name": "Indian Space Research Organisation", "short": "ISRO", "url": "https://www.isro.gov.in/Careers"},
    {"name": "Defence Research & Development Organisation", "short": "DRDO", "url": "https://www.drdo.gov.in/careers"},
    {"name": "National Informatics Centre", "short": "NIC", "url": "https://www.nic.in/careers"},
    {"name": "National Institute of Electronics & IT", "short": "NIELIT", "url": "https://www.nielit.gov.in/careers"},
    {"name": "Staff Selection Commission", "short": "SSC", "url": "https://ssc.nic.in"},
    {"name": "Railway Recruitment Board", "short": "RRB", "url": "https://www.rrbcdg.gov.in"},
    {"name": "Nuclear Power Corporation of India Limited", "short": "NPCIL", "url": "https://www.npcil.nic.in/careers"},
    {"name": "Housing & Urban Development Corporation", "short": "HUDCO", "url": "https://www.hudco.org.in/careers"},
    {"name": "Life Insurance Corporation of India", "short": "LIC", "url": "https://www.licindia.in/careers"},
    {"name": "General Insurance Corporation of India", "short": "GIC", "url": "https://www.gicre.in/careers"},
    {"name": "National Highways Authority of India", "short": "NHAI", "url": "https://www.nhai.gov.in/careers"},
    {"name": "Mumbai Railway Vikas Corporation", "short": "MRVC", "url": "https://www.mrvc.indianrailways.gov.in"},
    {"name": "Konkan Railway Corporation", "short": "KRCL", "url": "https://www.konkanrailway.com/careers"},
    {"name": "Delhi Metro Rail Corporation", "short": "DMRC", "url": "https://www.delhimetrorail.com/careers"},
    {"name": "Chennai Metro Rail Limited", "short": "CMRL", "url": "https://www.chennaimetrorail.org/careers"},
    {"name": "Bangalore Metro Rail Corporation", "short": "BMRCL", "url": "https://www.bmrc.co.in/careers"},
    {"name": "Mumbai Metro Rail Corporation", "short": "MMRCL", "url": "https://www.mmrcl.com/careers"},
    {"name": "Kolkata Metro Rail Corporation", "short": "KMRC", "url": "https://www.kmrc.in/careers"},
    {"name": "Cochin International Airport Limited", "short": "CIAL", "url": "https://www.cial.aero/careers"},
    {"name": "Bangalore International Airport Limited", "short": "BIAL", "url": "https://www.bengaluruairport.com/careers"},
    {"name": "Mumbai International Airport Limited", "short": "MIAL", "url": "https://www.csiamumbai.com/careers"},
    {"name": "Delhi International Airport Limited", "short": "DIAL", "url": "https://www.dial.co.in/careers"},
    {"name": "Hyderabad Metropolitan Water Supply & Sewerage Board", "short": "HMWSSB", "url": ""},
    {"name": "Chennai Metropolitan Water Supply & Sewerage Board", "short": "CMWSSB", "url": ""},
    {"name": "Delhi Jal Board", "short": "DJB", "url": "https://www.delhi.gov.in/djb/careers"},
]


ALL_PSUS = MAHARATNA_PSUS + NAVRATNA_PSUS + MINIRATNA_I_PSUS + MINIRATNA_II_PSUS + OTHER_PSUS


PSU_NAMES_FOR_FILTER = [
    # Maharatna
    "bharat heavy electricals", "bhel", "bharat petroleum", "bpcl",
    "coal india", "cil", "gail", "gail india",
    "hindustan petroleum", "hpcl", "indian oil", "iocl",
    "ntpc", "oil and natural gas", "ongc",
    "power finance corporation", "pfc",
    "rec limited", "rec", "oil india",
    "power grid", "pgcil", "steel authority", "sail",
    "hindustan aeronautics", "hal",
    # Navratna
    "bharat electronics", "bel",
    "container corporation", "concor",
    "engineers india", "eil",
    "mahanagar telephone", "mtnl",
    "national aluminium", "nalco",
    "national buildings construction", "nbcc",
    "nmdc", "rashtriya ispat", "rinl",
    "shipping corporation", "sci",
    "telecommunications consultants", "tcil",
    # Miniratna I
    "airports authority", "aai",
    "antrix", "balmer lawrie",
    "bharat coking", "bccl",
    "bharat dynamics", "bdl",
    "beml", "bharat sanchar", "bsnl",
    "central coalfields", "ccl",
    "central electronics", "cel",
    "central warehousing", "cwc",
    "cochin shipyard", "csl",
    "food corporation", "fci",
    "garden reach", "grse",
    "goa shipyard", "gsl",
    "hindustan copper", "hcl",
    "hll lifecare",
    "hscc india",
    "india tourism", "itdc",
    "indian rare earths", "irel",
    "ireda", "kiocl",
    "mazagon dock", "mdl",
    "mahanadi coalfields", "mcl",
    "manganese ore", "moil",
    "mishra dhatu", "midhani",
    "mstc", "national fertilizers", "nfl",
    "npcc", "nsic",
    "nhpc", "nlc india", "nlc",
    "numaligarh refinery", "nrl",
    "rashtriya chemicals", "rcf",
    "sjvn", "spmcil",
    "south eastern coalfields", "secl",
    "state trading", "stc",
    "thdc", "uranium corporation", "ucil",
    "wapcos", "western coalfields", "wcl",
    # Other PSUs
    "electronics corporation of india", "ecil",
    "bhabha atomic", "barc",
    "indian space research", "isro",
    "defence research", "drdo", "ceptam",
    "national informatics", "nic",
    "nielit",
    "staff selection commission", "ssc",
    "railway recruitment", "rrb", "indian railways",
    "nuclear power corporation", "npcil",
    "hudco", "life insurance", "lic",
    "general insurance", "gic",
    "national highways", "nhai",
    "delhi metro", "dmrc",
    "bangalore metro", "bmrcl",
    "chennai metro", "cmrl",
    "mumbai metro", "mmrcl",
    "konkan railway", "krcl",
    "cochin international airport", "cial",
    "delhi jal board", "djb",
]
