SEED_JOBS = [
    # ========== MAHARATNA PSUs ==========
    {
        "job_id": "bhel_2026_001",
        "title": "Graduate Engineer Trainee (Computer Science)",
        "organization": "Bharat Heavy Electricals Limited (BHEL)",
        "location": "Multiple Locations India",
        "eligibility": "B.E./B.Tech CSE/IT (65% aggregate)",
        "selection_process": "BHEL Written Test + Interview | Non-GATE",
        "posted_date": "2026-05-20",
        "deadline": "2026-06-15",
        "apply_url": "https://www.bhel.com/careers",
        "description": "BHEL recruitment for CSE trainees through own written exam. No GATE score required. BE/BTech CSE eligible for 2023-2026 batches.",
        "is_non_gate": True,
        "tags": ["Maharatna PSU", "CBT", "Engineer Trainee"],
        "batch_years": ["2023", "2024", "2025", "2026"]
    },
    {
        "job_id": "bpcl_2026_001",
        "title": "Management Trainee (Information Technology)",
        "organization": "Bharat Petroleum Corporation Limited (BPCL)",
        "location": "Mumbai, Delhi, Chennai",
        "eligibility": "B.E./B.Tech Computer Science / IT",
        "selection_process": "BPCL Recruitment Test + GD + Interview | Non-GATE",
        "posted_date": "2026-05-18",
        "deadline": "2026-06-10",
        "apply_url": "https://www.bharatpetroleum.in/careers",
        "description": "BPCL recruitment for IT through own exam. Maharatna PSU. Open for 2023-2026 batch graduates.",
        "is_non_gate": True,
        "tags": ["Maharatna PSU", "Own Exam"],
        "batch_years": ["2023", "2024", "2025", "2026"]
    },
    {
        "job_id": "cil_2026_001",
        "title": "Management Trainee (Information Technology)",
        "organization": "Coal India Limited (CIL)",
        "location": "Kolkata / Across India",
        "eligibility": "B.E/B.Tech CSE/IT",
        "selection_process": "CIL Written Test + Interview | Non-GATE",
        "posted_date": "2026-05-22",
        "deadline": "2026-06-20",
        "apply_url": "https://www.coalindia.in/careers",
        "description": "Coal India MT recruitment for IT discipline. Maharatna PSU. Own exam based selection. 2023-2026 batches eligible.",
        "is_non_gate": True,
        "tags": ["Maharatna PSU", "Written Test"],
        "batch_years": ["2023", "2024", "2025", "2026"]
    },
    {
        "job_id": "gail_2026_001",
        "title": "Executive Trainee (Computer Science)",
        "organization": "GAIL (India) Limited",
        "location": "New Delhi / Multiple Locations",
        "eligibility": "B.E/B.Tech CSE/IT",
        "selection_process": "GAIL Written Test + GD + Interview",
        "posted_date": "2026-05-15",
        "deadline": "2026-06-05",
        "apply_url": "https://gailonline.com/careers",
        "description": "GAIL ET recruitment for CSE stream. Maharatna PSU. Non-GATE route available. Freshers from 2023-2026 batches.",
        "is_non_gate": True,
        "tags": ["Maharatna PSU", "Own Exam"],
        "batch_years": ["2023", "2024", "2025", "2026"]
    },
    {
        "job_id": "hpcl_2026_001",
        "title": "Management Trainee (Information Technology)",
        "organization": "Hindustan Petroleum Corporation Limited (HPCL)",
        "location": "Mumbai, Delhi, Chennai",
        "eligibility": "B.E./B.Tech Computer Science / IT",
        "selection_process": "HPCL Recruitment Test (HRT) + GD + Interview",
        "posted_date": "2026-05-18",
        "deadline": "2026-06-10",
        "apply_url": "https://www.hpclcareers.com",
        "description": "Non-GATE stream for IT/CS. HPCL conducts independent exam for MT (IT). Graduate Engineers from 2023-2026 batches eligible.",
        "is_non_gate": True,
        "tags": ["Maharatna PSU", "Own Exam"],
        "batch_years": ["2023", "2024", "2025", "2026"]
    },
    {
        "job_id": "iocl_2026_001",
        "title": "Engineer Trainee (Information Technology)",
        "organization": "Indian Oil Corporation Limited (IOCL)",
        "location": "Multiple Locations India",
        "eligibility": "B.E/B.Tech CSE/IT",
        "selection_process": "IOCL Written Test + Interview",
        "posted_date": "2026-05-25",
        "deadline": "2026-06-20",
        "apply_url": "https://iocl.com/careers",
        "description": "IOCL recruitment for IT engineers. India's largest Maharatna PSU. Non-GATE route for freshers. 2023-2026 batch.",
        "is_non_gate": True,
        "tags": ["Maharatna PSU", "Own Exam"],
        "batch_years": ["2023", "2024", "2025", "2026"]
    },
    {
        "job_id": "ntpc_2026_001",
        "title": "Executive Trainee (Computer Science)",
        "organization": "NTPC Limited",
        "location": "Multiple Locations India",
        "eligibility": "B.E/B.Tech CSE/IT (65% aggregate)",
        "selection_process": "NTPC Written Test + Interview | Non-GATE stream available",
        "posted_date": "2026-05-12",
        "deadline": "2026-06-08",
        "apply_url": "https://www.ntpccareers.net",
        "description": "NTPC ET recruitment for CSE/IT. Maharatna PSU. Own exam based selection for non-GATE candidates. 2023-2026 batches.",
        "is_non_gate": True,
        "tags": ["Maharatna PSU", "Own Exam"],
        "batch_years": ["2023", "2024", "2025", "2026"]
    },
    {
        "job_id": "ongc_2026_001",
        "title": "Assistant Executive Engineer (IT/Computer Science)",
        "organization": "Oil and Natural Gas Corporation Limited (ONGC)",
        "location": "Multiple Locations India",
        "eligibility": "B.E/B.Tech CSE/IT",
        "selection_process": "ONGC Written Test + Interview",
        "posted_date": "2026-05-10",
        "deadline": "2026-06-05",
        "apply_url": "https://www.ongcindia.com/careers",
        "description": "ONGC recruitment for IT engineers. India's largest Maharatna PSU. Non-GATE recruitment drive for 2023-2026 batch graduates.",
        "is_non_gate": True,
        "tags": ["Maharatna PSU", "Own Exam"],
        "batch_years": ["2023", "2024", "2025", "2026"]
    },
    {
        "job_id": "sail_2026_001",
        "title": "Management Trainee (Computer Science)",
        "organization": "Steel Authority of India Limited (SAIL)",
        "location": "Multiple Locations India",
        "eligibility": "B.E/B.Tech CSE/IT",
        "selection_process": "SAIL Written Test + Interview | Non-GATE",
        "posted_date": "2026-05-19",
        "deadline": "2026-06-15",
        "apply_url": "https://www.sail.co.in/careers",
        "description": "SAIL MT recruitment for CSE/IT. Maharatna PSU. Own exam based. Freshers from 2023-2026 batches eligible.",
        "is_non_gate": True,
        "tags": ["Maharatna PSU", "Own Exam"],
        "batch_years": ["2023", "2024", "2025", "2026"]
    },
    {
        "job_id": "pgcil_2026_001",
        "title": "Assistant Engineer Trainee (IT)",
        "organization": "Power Grid Corporation of India Limited (PGCIL)",
        "location": "Multiple Locations India",
        "eligibility": "B.E/B.Tech CSE/IT",
        "selection_process": "PGCIL Written Test + Interview",
        "posted_date": "2026-05-21",
        "deadline": "2026-06-18",
        "apply_url": "https://www.powergrid.in/careers",
        "description": "PGCIL recruitment for IT trainees. Maharatna PSU. Non-GATE route. 2023-2026 batch graduates can apply.",
        "is_non_gate": True,
        "tags": ["Maharatna PSU", "Own Exam"],
        "batch_years": ["2023", "2024", "2025", "2026"]
    },
    {
        "job_id": "oil_2026_001",
        "title": "Management Trainee (IT)",
        "organization": "Oil India Limited (OIL)",
        "location": "Duliajan / Multiple Locations",
        "eligibility": "B.E/B.Tech CSE/IT",
        "selection_process": "Oil India Written Test + Interview",
        "posted_date": "2026-05-24",
        "deadline": "2026-06-20",
        "apply_url": "https://www.oil-india.com/careers",
        "description": "Oil India recruitment for IT stream. Maharatna PSU. Own exam based. 2023-2026 batch freshers welcome.",
        "is_non_gate": True,
        "tags": ["Maharatna PSU", "Own Exam"],
        "batch_years": ["2023", "2024", "2025", "2026"]
    },
    {
        "job_id": "hal_2026_001",
        "title": "Trainee Engineer (IT) - Own Recruitment Drive",
        "organization": "Hindustan Aeronautics Limited (HAL)",
        "location": "Bengaluru, Koraput",
        "eligibility": "B.E/B.Tech CSE/IT",
        "selection_process": "HAL Written Examination + Interview (Non-GATE mode)",
        "posted_date": "2026-05-24",
        "deadline": "2026-06-25",
        "apply_url": "https://hal-india.co.in/careers",
        "description": "HAL recruitment for IT discipline through All India test. Maharatna PSU. GATE not required for this stream. 2023-2026 batches.",
        "is_non_gate": True,
        "tags": ["Aerospace PSU", "Own Exam"],
        "batch_years": ["2023", "2024", "2025", "2026"]
    },
    # ========== NAVRATNA PSUs ==========
    {
        "job_id": "bel_2026_001",
        "title": "Graduate Engineer Trainee (Computer Science)",
        "organization": "Bharat Electronics Limited (BEL)",
        "location": "Bangalore / Ghaziabad",
        "eligibility": "B.E./B.Tech CSE/IT (65% aggregate)",
        "selection_process": "CBT (Computer Based Test) + Interview | No GATE",
        "posted_date": "2026-05-20",
        "deadline": "2026-06-15",
        "apply_url": "https://bel-india.in/careers",
        "description": "BEL recruitment for CSE trainees through own national level written exam. Navratna PSU. 2023-2026 batch graduates.",
        "is_non_gate": True,
        "tags": ["Navratna PSU", "CBT", "Engineer Trainee"],
        "batch_years": ["2023", "2024", "2025", "2026"]
    },
    {
        "job_id": "mtnl_2026_001",
        "title": "Executive Trainee (IT)",
        "organization": "Mahanagar Telephone Nigam Limited (MTNL)",
        "location": "Mumbai, Delhi",
        "eligibility": "B.E/B.Tech CSE/IT",
        "selection_process": "MTNL Written Test + Interview",
        "posted_date": "2026-05-16",
        "deadline": "2026-06-12",
        "apply_url": "https://www.mtnl.co.in/careers",
        "description": "MTNL recruitment for IT executives. Navratna PSU. Telecom sector. Freshers from 2023-2026 batches.",
        "is_non_gate": True,
        "tags": ["Navratna PSU", "Telecom"],
        "batch_years": ["2023", "2024", "2025", "2026"]
    },
    {
        "job_id": "nmdc_2026_001",
        "title": "Junior Officer (IT)",
        "organization": "NMDC Limited",
        "location": "Hyderabad / Multiple Locations",
        "eligibility": "B.E/B.Tech CSE/IT",
        "selection_process": "NMDC Written Test + Interview",
        "posted_date": "2026-05-23",
        "deadline": "2026-06-18",
        "apply_url": "https://www.nmdc.co.in/careers",
        "description": "NMDC recruitment for IT officers. India's largest iron ore producer. Navratna PSU. 2023-2026 batch graduates.",
        "is_non_gate": True,
        "tags": ["Navratna PSU", "Mining"],
        "batch_years": ["2023", "2024", "2025", "2026"]
    },
    # ========== MINIRATNA PSUs ==========
    {
        "job_id": "ecil_2026_001",
        "title": "Engineer Trainee (Computer Science & Information Security)",
        "organization": "Electronics Corporation of India Limited (ECIL)",
        "location": "Hyderabad",
        "eligibility": "B.E/B.Tech CSE/IT, 1st class",
        "selection_process": "ECIL Written Test (Technical) + Trade Test",
        "posted_date": "2026-05-22",
        "deadline": "2026-06-20",
        "apply_url": "https://www.ecil.co.in/careers",
        "description": "ECIL \u2013 A Govt of India Enterprise. Direct recruitment via own exam. No GATE required. 2023-2026 batch graduates.",
        "is_non_gate": True,
        "tags": ["PSU", "Written Test"],
        "batch_years": ["2023", "2024", "2025", "2026"]
    },
    {
        "job_id": "fci_2026_001",
        "title": "Manager (IT) Trainee",
        "organization": "Food Corporation of India (FCI)",
        "location": "Multiple Locations India",
        "eligibility": "B.E/B.Tech CSE/IT",
        "selection_process": "FCI Written Test + Interview",
        "posted_date": "2026-05-14",
        "deadline": "2026-06-10",
        "apply_url": "https://www.fci.gov.in/careers",
        "description": "FCI recruitment for IT managers. Miniratna PSU. Own exam based. 2023-2026 batch graduates.",
        "is_non_gate": True,
        "tags": ["Miniratna PSU", "Food Sector"],
        "batch_years": ["2023", "2024", "2025", "2026"]
    },
    {
        "job_id": "bsnl_2026_001",
        "title": "Junior Telecom Officer (IT)",
        "organization": "Bharat Sanchar Nigam Limited (BSNL)",
        "location": "Across India",
        "eligibility": "B.E/B.Tech CSE/IT/EC",
        "selection_process": "BSNL Written Test + Interview",
        "posted_date": "2026-05-11",
        "deadline": "2026-06-07",
        "apply_url": "https://www.bsnl.co.in/careers",
        "description": "BSNL recruitment for IT officers. Miniratna PSU. Telecom sector. Non-GATE. 2023-2026 batch.",
        "is_non_gate": True,
        "tags": ["Miniratna PSU", "Telecom"],
        "batch_years": ["2023", "2024", "2025", "2026"]
    },
    {
        "job_id": "aai_2026_001",
        "title": "Junior Executive (IT)",
        "organization": "Airports Authority of India (AAI)",
        "location": "Across India",
        "eligibility": "B.E/B.Tech CSE/IT",
        "selection_process": "AAI Written Test + Interview",
        "posted_date": "2026-05-17",
        "deadline": "2026-06-12",
        "apply_url": "https://www.aai.aero/careers",
        "description": "AAI recruitment for IT junior executives. Miniratna PSU. Airport sector. 2023-2026 batch graduates.",
        "is_non_gate": True,
        "tags": ["Miniratna PSU", "Aviation"],
        "batch_years": ["2023", "2024", "2025", "2026"]
    },
    {
        "job_id": "nhpc_2026_001",
        "title": "Executive Trainee (IT)",
        "organization": "NHPC Limited",
        "location": "Multiple Locations India",
        "eligibility": "B.E/B.Tech CSE/IT",
        "selection_process": "NHPC Written Test + Interview",
        "posted_date": "2026-05-13",
        "deadline": "2026-06-09",
        "apply_url": "https://www.nhpcindia.com/careers",
        "description": "NHPC recruitment for IT executives. Miniratna PSU. Hydropower sector. 2023-2026 batch freshers.",
        "is_non_gate": True,
        "tags": ["Miniratna PSU", "Power"],
        "batch_years": ["2023", "2024", "2025", "2026"]
    },
    {
        "job_id": "nlc_2026_001",
        "title": "Graduate Engineer Trainee (IT)",
        "organization": "NLC India Limited",
        "location": "Neyveli / Multiple Locations",
        "eligibility": "B.E/B.Tech CSE/IT",
        "selection_process": "NLC Written Test + Interview",
        "posted_date": "2026-05-20",
        "deadline": "2026-06-15",
        "apply_url": "https://www.nlcindia.com/careers",
        "description": "NLC India GET recruitment for IT. Miniratna PSU. Lignite mining & power. 2023-2026 batch.",
        "is_non_gate": True,
        "tags": ["Miniratna PSU", "Power"],
        "batch_years": ["2023", "2024", "2025", "2026"]
    },
    {
        "job_id": "midhani_2026_001",
        "title": "Engineer Trainee (IT)",
        "organization": "Mishra Dhatu Nigam Limited (MIDHANI)",
        "location": "Hyderabad",
        "eligibility": "B.E/B.Tech CSE/IT",
        "selection_process": "MIDHANI Written Test + Interview",
        "posted_date": "2026-05-26",
        "deadline": "2026-06-20",
        "apply_url": "https://www.midhani.gov.in/careers",
        "description": "MIDHANI recruitment for IT trainees. Miniratna PSU. Defence sector. 2023-2026 batch.",
        "is_non_gate": True,
        "tags": ["Miniratna PSU", "Defence"],
        "batch_years": ["2023", "2024", "2025", "2026"]
    },
    # ========== OTHER PSUs ==========
    {
        "job_id": "isro_2026_001",
        "title": "Scientist/Engineer Trainee (Computer Science)",
        "organization": "ISRO \u2013 Indian Space Research Organisation",
        "location": "Multiple Centers (Bengaluru, Ahmedabad)",
        "eligibility": "B.E/B.Tech CSE with 65%",
        "selection_process": "ISRO Centralised Recruitment Exam (ICRB) \u2013 No GATE needed for Trainee posts",
        "posted_date": "2026-05-15",
        "deadline": "2026-06-05",
        "apply_url": "https://www.isro.gov.in/Careers",
        "description": "ISRO entry for Engineers through ICRB. Non-GATE route available for freshers from 2023-2026 batches.",
        "is_non_gate": True,
        "tags": ["Space PSU", "ICRB"],
        "batch_years": ["2023", "2024", "2025", "2026"]
    },
    {
        "job_id": "drdo_2026_001",
        "title": "Junior Research Fellow / Trainee (CSE/IT) - Non-GATE",
        "organization": "DRDO (CEPTAM)",
        "location": "Delhi, Pune, Hyderabad",
        "eligibility": "B.E/B.Tech CSE/IT",
        "selection_process": "CEPTAM Written Exam + Interview",
        "posted_date": "2026-05-10",
        "deadline": "2026-06-01",
        "apply_url": "https://www.drdo.gov.in/careers",
        "description": "DRDO\u2019s Centre for Personnel Talent Management (CEPTAM) recruits technical trainees without GATE. 2023-2026 batches.",
        "is_non_gate": True,
        "tags": ["Defence PSU", "CEPTAM"],
        "batch_years": ["2023", "2024", "2025", "2026"]
    },
    {
        "job_id": "barc_2026_001",
        "title": "Engineer Trainee (Computer Science) \u2013 BARC Training Scheme",
        "organization": "Bhabha Atomic Research Centre (BARC)",
        "location": "Mumbai",
        "eligibility": "B.E/B.Tech CSE, aggregate minimum 60%",
        "selection_process": "BARC Online Examination (OCES/DGFS) - GATE not compulsory for specific trainee stream",
        "posted_date": "2026-05-12",
        "deadline": "2026-06-07",
        "apply_url": "https://www.barc.gov.in/careers",
        "description": "BARC OCES/DGFS training scheme. GATE not mandatory. Based on BARC screening test. 2023-2026 graduates.",
        "is_non_gate": True,
        "tags": ["Atomic Energy", "OCES"],
        "batch_years": ["2023", "2024", "2025", "2026"]
    },
    {
        "job_id": "ssc_2026_001",
        "title": "IT Engineer Trainee (Combined Graduate Level Exam \u2013 SSC CGL for IT Posts)",
        "organization": "Staff Selection Commission (SSC)",
        "location": "Across India",
        "eligibility": "Bachelor's in Computer Science / IT / BCA",
        "selection_process": "SSC CGL Tier I, II, III, IV \u2013 No GATE",
        "posted_date": "2026-05-05",
        "deadline": "2026-06-30",
        "apply_url": "https://ssc.nic.in",
        "description": "SSC CGL includes posts like Assistant (IT), Auditor (IT). Open for computer engineers. Non-GATE government job. 2023+ batch.",
        "is_non_gate": True,
        "tags": ["Central Govt", "SSC Exam"],
        "batch_years": ["2023", "2024", "2025", "2026"]
    },
    {
        "job_id": "rrb_2026_001",
        "title": "Junior Engineer (Information Technology)",
        "organization": "Indian Railways (RRB)",
        "location": "Zonal Railways Pan India",
        "eligibility": "B.E/B.Tech in CS/IT or equivalent",
        "selection_process": "RRB JE CBT-1 and CBT-2 | No GATE requirement",
        "posted_date": "2026-05-19",
        "deadline": "2026-07-10",
        "apply_url": "https://www.rrbcdg.gov.in",
        "description": "RRB Junior Engineer (JE) notification for IT/CS stream. Indian railways recruitment board exam. Non-GATE. 2023-2026 batches.",
        "is_non_gate": True,
        "tags": ["Railways", "JE"],
        "batch_years": ["2023", "2024", "2025", "2026"]
    },
    {
        "job_id": "nic_2026_001",
        "title": "Technical Trainee (Computer Science) \u2013 Direct recruitment",
        "organization": "National Informatics Centre (NIC) / NIELIT",
        "location": "New Delhi / Regional Centers",
        "eligibility": "B.E/B.Tech CSE/IT",
        "selection_process": "Written Exam + Interview (No GATE score required)",
        "posted_date": "2026-05-21",
        "deadline": "2026-06-18",
        "apply_url": "https://www.nic.in/careers",
        "description": "NIC recruitment for computer engineer trainees. Government IT. 2023-2026 batch graduates.",
        "is_non_gate": True,
        "tags": ["Govt IT", "NIELIT"],
        "batch_years": ["2023", "2024", "2025", "2026"]
    },
    {
        "job_id": "npcil_2026_001",
        "title": "Executive Trainee (Computer Science)",
        "organization": "Nuclear Power Corporation of India Limited (NPCIL)",
        "location": "Multiple Locations India",
        "eligibility": "B.E/B.Tech CSE/IT",
        "selection_process": "NPCIL Written Test + Interview",
        "posted_date": "2026-05-16",
        "deadline": "2026-06-12",
        "apply_url": "https://www.npcil.nic.in/careers",
        "description": "NPCIL recruitment for CS trainees. Nuclear energy sector. 2023-2026 batch graduates.",
        "is_non_gate": True,
        "tags": ["Nuclear PSU", "Energy"],
        "batch_years": ["2023", "2024", "2025", "2026"]
    },
    {
        "job_id": "dmrc_2026_001",
        "title": "Assistant Manager (IT)",
        "organization": "Delhi Metro Rail Corporation (DMRC)",
        "location": "Delhi NCR",
        "eligibility": "B.E/B.Tech CSE/IT",
        "selection_process": "DMRC Written Test + Interview",
        "posted_date": "2026-05-23",
        "deadline": "2026-06-15",
        "apply_url": "https://www.delhimetrorail.com/careers",
        "description": "DMRC recruitment for IT managers. Metro rail sector. 2023-2026 batch graduates.",
        "is_non_gate": True,
        "tags": ["Metro Rail", "Transport"],
        "batch_years": ["2023", "2024", "2025", "2026"]
    },
    {
        "job_id": "lic_2026_001",
        "title": "Assistant Administrative Officer (IT)",
        "organization": "Life Insurance Corporation of India (LIC)",
        "location": "Multiple Locations India",
        "eligibility": "B.E/B.Tech CSE/IT",
        "selection_process": "LIC AAO Exam + Interview",
        "posted_date": "2026-05-09",
        "deadline": "2026-06-05",
        "apply_url": "https://www.licindia.in/careers",
        "description": "LIC AAO recruitment for IT specialists. Insurance sector. 2023-2026 batch graduates.",
        "is_non_gate": True,
        "tags": ["Insurance PSU", "AAO"],
        "batch_years": ["2023", "2024", "2025", "2026"]
    },
]
